# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-12-14 14:45+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: apps/analyzer/collect_results.py:53
msgid "Warning: GUI component appears more than twice"
msgstr ""
"Advertencia: el componente de la interfaz gráfica aparece más de dos veces"

#: apps/analyzer/collect_results.py:66
msgid "GUI component quantity difference greater than the expected"
msgstr ""
"La diferencia de cantidad de componentes de la interfaz gráfica es mayor de "
"lo esperado"

#: apps/analyzer/collect_results.py:106
#, fuzzy, python-format
#| msgid "Condition %(expression) is not fulfilled"
msgid "Condition %(expression) is not fulfilled"
msgstr "La condición %(expression) no se cumple"

#: apps/analyzer/collect_results.py:147 apps/analyzer/collect_results.py:258
msgid "Experiment results that have been processed"
msgstr "Resultados del experimento que han sido procesados"

#: apps/analyzer/collect_results.py:310
msgid "DECISION TREE results collection fail! :("
msgstr "¡Fallo en la recolección de resultados del ÁRBOL DE DECISIÓN! :("

#: apps/analyzer/forms.py:42
msgid "Nice experiment title!"
msgstr "Un buen título para el experimento"

#: apps/analyzer/forms.py:48
msgid "Short experiment description..."
msgstr "Descripción breve del experimento..."

#: apps/analyzer/forms.py:110
msgid "Variant"
msgstr "Variante"

#: apps/analyzer/forms.py:149
msgid "Title is taken"
msgstr "El título ya ha sido utilizado"

#: apps/analyzer/models.py:50
msgid "exp_folder_complete_path separators not coherent"
msgstr "Los separadores de exp_folder_complete_path no son coherentes"

#: apps/analyzer/models.py:56
msgid "This is a nice experiment..."
msgstr "Este es un buen experimento..."

#: apps/analyzer/models.py:66
msgid "CheckBox_4_D or ImageView_4_D or TextView_4_D"
msgstr "CheckBox_4_D o ImageView_4_D o TextView_4_D"

#: apps/analyzer/models.py:81
msgid "Case study"
msgstr "Caso de estudio"

#: apps/analyzer/models.py:82
msgid "Case studies"
msgstr "Casos de estudio"

#: apps/analyzer/models.py:118
msgid "The title of the case study already exists"
msgstr "El título del caso de estudio ya existe"

#: apps/analyzer/utils.py:44
msgid ""
"analyzer/utils/store_screenshots. line 49. MIME Html format not contains "
"Content-Location header in screenshots"
msgstr ""
"El formato MIME Html no contiene encabezado Content-Location en las capturas "
"de pantalla"

#: apps/analyzer/utils.py:45
msgid "MIME Html format not contains Content-Location header in screenshots"
msgstr ""
"El formato MIME Html no contiene encabezado Content-Location en las capturas "
"de pantalla"

#: apps/analyzer/utils.py:183
msgid ""
"analyzer/utils/format_mht_file. line 187. MHT file format selected doesnt "
"exists"
msgstr ""
"analyzer/utils/format_mht_file. line 187. Se seleccionó un formato de "
"archivo MHT que no existe"

#: apps/analyzer/utils.py:184
msgid "You select a format mht file that doesnt exists"
msgstr "Has seleccionado un archivo MHT que no existe"

#: apps/analyzer/utils.py:213
msgid ""
"analyzer/utils/format_mht_file. line 211. The MHT file doesnt follows the "
"format:'Step 1: (datetime)'"
msgstr ""
"analyzer/utils/format_mht_file. line 211. El archivo MHT no sigue el "
"formato: 'Paso 1: (datetime)'"

#: apps/analyzer/utils.py:214
msgid "The MHT file doesnt have '(datetime)' after 'Step 1:'"
msgstr "El archivo MHT no tiene '(datetime)' después de 'Paso 1:'"

#: apps/analyzer/utils.py:223
msgid "The MHT file doesnt have a valid datetime format"
msgstr "El archivo MHT no tiene un formato de fecha y hora válido"

#: apps/analyzer/views.py:123
msgid "Scenarios that have been processed: "
msgstr "Escenarios que han sido procesados: "

#: apps/analyzer/views.py:146
msgid ""
"There's no phase to execute or the specified phase doesn't corresponds to a "
"supported one"
msgstr ""
"No hay una fase para ejecutar o la fase especificada no corresponde a una "
"admitida"

#: apps/analyzer/views.py:160
msgid ""
"Case study '%(title)' executed!!. Case study foldername: %(exp_foldername). "
"Metadata saved in: %(metadata_final_path)"
msgstr ""
"¡Caso de estudio '%(title)' ejecutado! Nombre de la carpeta del caso de "
"estudio: %(exp_foldername). Metadatos guardados en: %(metadata_final_path)"

#: apps/analyzer/views.py:274
msgid "User must be authenticated."
msgstr "El usuario debe estar autenticado."

#: apps/analyzer/views.py:294 apps/analyzer/views.py:308
msgid "This case study doesn't belong to the authenticated user"
msgstr "Este caso de estudio no pertenece al usuario autenticado"

#: apps/analyzer/views.py:296
msgid "There's no phase to execute"
msgstr "No hay una fase para ejecutar"

#: apps/analyzer/views.py:310
#, fuzzy
#| msgid ""
#| "This case study cannot be deleted because it has already been executed"
msgid "This case study cannot be deleted because it has already been excecuted"
msgstr "Este caso de estudio no se puede eliminar porque ya ha sido ejecutado"

#: apps/analyzer/views.py:346
#, python-format
msgid ""
"phases_to_execute must be of type dict!!!!! and must be composed by phases "
"contained in %(DEFAULT_PHASES)s"
msgstr ""
"¡phases_to_execute debe ser de tipo dict y debe estar compuesto por fases "
"contenidas en %(DEFAULT_PHASES)s!"

#: apps/analyzer/views.py:352
msgid "Elements Detection algorithm must be one of ['legacy', 'uied']"
msgstr ""
"El algoritmo de detección de elementos debe ser uno de ['legacy', 'uied']"

#: apps/analyzer/views.py:359
msgid "Elements Classification algorithm must be one of ['legacy', 'uied']"
msgstr ""
"El algoritmo de clasificación de elementos debe ser uno de ['legacy', 'uied']"

#: apps/analyzer/views.py:367 apps/analyzer/views.py:373
msgid "The following file or directory does not exists: %(path)"
msgstr "El siguiente archivo o directorio no existe: %(path)"

#: apps/analyzer/views.py:380
#, python-format
msgid ""
"phases_to_execute must be composed by phases contained in %(DEFAULT_PHASES)s"
msgstr ""
"phases_to_execute debe estar compuesto por fases contenidas en "
"%(DEFAULT_PHASES)s"

#: apps/analyzer/views.py:393
#, fuzzy, python-format
#| msgid "Case study with id:%(id) is being generated ..."
msgid "Case study with id:%(id) is being generated ..."
msgstr "Se está generando el caso de estudio con ID:%(id) ..."

#: apps/analyzer/views.py:396
msgid "Some of the attributes are invalid: "
msgstr "Algunos de los atributos no son válidos: "

#: apps/analyzer/views.py:415
msgid "Case Study with id %(id) not found"
msgstr "Caso de estudio con ID %(id) no encontrado"

#: apps/analyzer/views.py:433
msgid ""
"The processing of this case study has not yet finished, please try again in "
"a few minutes"
msgstr ""
"El procesamiento de este caso de estudio aún no ha finalizado, por favor "
"inténtelo de nuevo en unos minutos"

#: apps/analyzer/views.py:436
#, fuzzy, python-format
#| msgid "Case Study with id %(id) raised an exception: "
msgid "Case Study with id %(id) raised an exception: "
msgstr "El caso de estudio con ID %(id) generó una excepción: "

#: apps/analyzer/views.py:490
msgid "You don't have permissions to access this files"
msgstr "No tienes permisos para acceder a estos archivos"
